import { FiberType, FiberRootMode, TrackingObjectType, TrackingObjectTypeHook } from "common-types";
export declare const ToolId = "React Render Tracker";
export declare const ElementTypeClass: FiberType;
export declare const ElementTypeFunction: FiberType;
export declare const ElementTypeMemo: FiberType;
export declare const ElementTypeForwardRef: FiberType;
export declare const ElementTypeProvider: FiberType;
export declare const ElementTypeConsumer: FiberType;
export declare const ElementTypeHostRoot: FiberType;
export declare const ElementTypeHostComponent: FiberType;
export declare const ElementTypeHostText: FiberType;
export declare const ElementTypeHostPortal: FiberType;
export declare const ElementTypeSuspense: FiberType;
export declare const ElementTypeSuspenseList: FiberType;
export declare const ElementTypeProfiler: FiberType;
export declare const ElementTypeOtherOrUnknown: FiberType;
export declare const FiberTypeName: Record<FiberType, string>;
export declare const LegacyRoot: FiberRootMode;
export declare const ConcurrentRoot: FiberRootMode;
export declare const fiberRootMode: Record<FiberRootMode, string>;
export declare const TrackingObjectFiber: TrackingObjectType;
export declare const TrackingObjectAlternate: TrackingObjectType;
export declare const TrackingObjectStateNode: TrackingObjectType;
export declare const TrackingObjectHook: TrackingObjectTypeHook;
export declare const TrackingObjectTypeName: Record<TrackingObjectType, string>;
export declare const FeatureMemLeaks = false;
export declare const FeatureCommits = false;
