import * as React from "react";
export declare const Search: React.JSX.Element;
export declare const ToggleGrouping: React.JSX.Element;
export declare const ClearEventLog: React.JSX.Element;
export declare const ToggleUnmounted: React.JSX.Element;
export declare const SubtreeToggle: React.JSX.Element;
export declare const ToggleTimings: React.JSX.Element;
export declare const ChevronUp: React.JSX.Element;
export declare const ChevronDown: React.JSX.Element;
export declare const Back: React.JSX.Element;
export declare const Forward: React.JSX.Element;
export declare const Pin: React.JSX.Element;
export declare const Cancel: React.JSX.Element;
export declare const BreakRefs: React.JSX.Element;
export declare const ExposeToGlobal: React.JSX.Element;
export declare const Download: React.JSX.Element;
export declare const Pause: React.JSX.Element;
export declare const Play: React.JSX.Element;
